library(shiny)
library(descriptr, lib.loc = "C:/Users/HP/Documents/R/win-library")
library(olsrr, lib.loc = "C:/Users/HP/Documents/R/win-library"  )
library(inferr, lib.loc = "C:/Users/HP/Documents/R/win-library"  )
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(purrr)
library(tidyr)
library(tibble)
library(readxl)
library(readr)
library(jsonlite)
library(magrittr)
library(tools)
library(caret)


shinyServer(function(input, output, session) {

	source('logic/logic_dataoptions.R', local = T)
    source('logic/logic_upload.R', local = T)
    source('logic/logic_transform2.R', local = T)
    source('logic/logic_select.R', local = T)
    source('logic/logic_filter.R', local = T)
    source('logic/logic_screen.R', local = T)
    source('logic/logic_sample.R', local = T)
    source('logic/logic_partition.R', local = T)
    source('logic/logic_view.R', local = T)
    source('logic/logic_summary.R', local = T)
    source('logic/logic_freq_qual.R', local = T)
    source('logic/logic_freq_quant.R', local = T)
    source('logic/logic_cross.R', local = T)
    source('logic/logic_mult1.R', local = T)
    source('logic/logic_mult2.R', local = T)
    source('logic/logic_group_summary.R', local = T)
    source('logic/logic_ttest.R', local = T)
    source('logic/logic_itest.R', local = T)
    source('logic/logic_ptest.R', local = T)
    source('logic/logic_binomtest.R', local = T)
    source('logic/logic_osvar.R', local = T)
    source('logic/logic_tsvar.R', local = T)
    source('logic/logic_osprop.R', local = T)
    source('logic/logic_tsprop.R', local = T)
    source('logic/logic_anova.R', local = T)
    source('logic/logic_levene.R', local = T)
    
})


